apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digital-ocean-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCApjY6GYzOu0mS4UIfCljZXib7yY57dq2Z1Nfm4tODD6K+7MydK6Az/M/7yX761gZ9MHtmS6hm/KwZu8Han1WLC/BK0E+w2KPtXXJAfiq58W4dAO532Ry5kQ5Sz3OVW8gscyFtyqSia+YsLo4ugduA3QAze3QGHG7pXOEZlIFyAhATwhH71uRTt61OiPgb7e/6553AKeN+ljaiPtiEVG1MytOQT8ETsUbk7ZrrXscKg7RRr/WD3jiBOZmdSlXpz7TndlOOi3zDsjns8+F1zhEC/1L0+BHUdkqm8pzQeDLqUms7kDfINFGvgK7yEeNqZeb6kX7SGUJbNiKv3vluO5z5IMPAPiG5IsYIIrrovF6Vn9hsdzBwhc2uW1cP3gp0aVkqtkGqIxHIFlPMe6KRXcD9NWGri7l3nG4QMxcF9p2XuIxr9NSMtmUr+0sD/fz8QR+Lhhh2IoLlXuLAQvGgVunDg5KOdyweSZY8zhZaSbGpK7+PfApGYMdqIoYKeNh6w9n2rtVw3JrkLpiyEwmNFyrNU/8IjCd12VbgtUElB/FhbWDHEXFcBzLw2zwi/0l9Yqj9V6nbreJKzqfHAnpQTU3tpj2vMJDdFV15TyUOiNiK5ZIIMQaMKWME3xoNmvp/cZuf2jB/s8djAwjMfSG4s5sJFFEtFQoqgchiWfRILnL2ZVK4CNImBCNVZg4ayfnE+W2y9EgvLzFQXgLPB+wiVuSjEw2CWvF0AYCFIW+deVPgJEfpkdqdxKi6/u0rBHwRl0g7bcAijqo9/EmIu7JKhC3t
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: digital-ocean-token
      namespace: flux-system

