apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digital-ocean-token
  namespace: crossplane-system
spec:
  encryptedData:
    token: AgCF2KaWGxH8I6sR3J1H8mBEeT5L3FcLO7e89JrTbh1pjBzn2PHlF03gD+BqokuN+5L06ryVs/gUdVelez1FUz88gK9i37nVAl/GV6Q9Wil08Xd+uSmvODTImUjUfZOeFsuPUcB6VcRNSqUupirOHWMkMKyineomyy//VVPhHQ31Eo4FHDgg3PrEw+1guFefJpG/IslgcWIWyT9976wWwS0nx9zkb9w45faTTuIrkbv4DE5L2ZrBtMA08Q7L5SyRf5lae01+1S3O+fR1Icg/BjLc1ONpr2lk0d0FZNE1nM+U4Hrs8dsaBPutEH/oAIMVfObS0DkVAsEMh6Vc+Vn6uLUI80JHBKs+nzzxrQlwRHDj+plfWI1hngg7nEytP4q5uX8fITjq7dVSAwevMq+yOd4EIftjVyWQvL/ZmhT5jjMEYEaGhq4Y59GC9Y3hatDUdrwRdI7tK6feWKUYXADuY8IVd7OvWImSz79/31S9DJqOMS83L3Hwdq7YvoHnRS7mSE0ebC4HltjGWo2weRwjAt739Gzs+JPegKCkgGBdUAI+oQcGWm2vf784xB0g4DH5JzETJD5D/XkzdQ6eE2IOIGuBenp42qvKZfW5jPk7e5TOsz4GAHcuFCS2Ej17zWUTKECUa7lmTeEIaHXUCYYPHnRETUE/w+3U81hcuX3wShfBfx4WYKPjx8/d6HKMx5iSEUd83MKu+GHKLzawxYSo/HUM3amuhVdZ+Cyt30jHq+tJy+Z8j+t6sFBEyLvbsGoQ7stVFBTt/sUrq+wjmBshhscV
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: digital-ocean-token
      namespace: crossplane-system

