---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-resources
  namespace: flux-system
spec:
  dependsOn:
  - name: crossplane-do-provider-config
  interval: 1m0s
  path: ./clusters/cluster01-apps/crossplane-resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: crossplane-resources

