---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane-do-provider
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/cluster01-apps/crossplane-do-provider
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

