---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-do-provider-config
  namespace: flux-system
spec:
  dependsOn:
    - name: crossplane-do-provider
  interval: 1m0s
  path: ./clusters/cluster01-apps/crossplane-do-provider-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: crossplane-system
